# Generated by Django 4.0.10 on 2024-08-12 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0005_book_id_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewSummaryOverall',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_summary', models.TextField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_summary', to='books.book')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewSummaryGenre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_genre', models.TextField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_genre', to='books.book')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewSummaryAuthor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_author', models.TextField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_author', to='books.book')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewStar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_star', models.DecimalField(decimal_places=2, max_digits=6)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_star', to='books.book')),
            ],
        ),
    ]
