# Generated by Django 4.0.10 on 2024-08-13 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_book_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='review_url',
            field=models.CharField(default='https://www.google.com/', max_length=500),
        ),
    ]
