# Generated by Django 4.0.10 on 2024-08-13 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0009_review_review_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='reviewer_name',
            field=models.CharField(default='SampleReviewer', max_length=200),
        ),
    ]
