# Generated by Django 4.0.10 on 2024-08-14 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0010_review_reviewer_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewSummaryGoodreads',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_goodreads', models.TextField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_goodreads', to='books.book')),
            ],
        ),
        migrations.CreateModel(
            name='ReviewSummaryAmazon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_amazon', models.TextField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_amazon', to='books.book')),
            ],
        ),
    ]
