# Generated by Django 4.0.10 on 2024-08-14 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0011_reviewsummarygoodreads_reviewsummaryamazon'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewstar',
            name='review_total_Ratings',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20),
        ),
    ]
