# Generated by Django 4.0.10 on 2024-08-15 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_reviewstar_review_total_ratings'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewsummaryamazon',
            name='review_amazon_star',
            field=models.DecimalField(decimal_places=2, default=2.5, max_digits=6),
        ),
        migrations.AddField(
            model_name='reviewsummarygoodreads',
            name='review_goodreads_star',
            field=models.DecimalField(decimal_places=2, default=2.5, max_digits=6),
        ),
        migrations.AddField(
            model_name='reviewsummaryoverall',
            name='review_bad',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='reviewsummaryoverall',
            name='review_good',
            field=models.TextField(default=''),
        ),
    ]
