# Generated by Django 4.0.10 on 2024-08-15 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_reviewsummaryamazon_review_amazon_star_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewsummaryamazon',
            name='review_amazon_ratings',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20),
        ),
        migrations.AddField(
            model_name='reviewsummarygoodreads',
            name='review_goodreads_ratings',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=20),
        ),
    ]
